[package]
name = "pokedex"
version = "0.1.0"
edition = "2021"
authors = ["boris.lok <boris.lok.tw@outlook.com>"]

[dependencies]
rouille = "3.6.2"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
clap = { version = "4.4.12", features = ["cargo"] }
dialoguer = "0.11.0"

